site_name: DRF 2Factor Authentication
site_description: Integrate 2 Factor Authentication in Your Django REST API project easily.
site_author: Farhad Hossain
copyright: © 2024, Farhad Hossain
extra:
  version: 1.0.4

repo_url: https://github.com/farhad0085/drf-2fa

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Usage: usage.md
  - Customization: customization.md
  - Settings: settings.md
  - API Reference:
      - API Reference: api_reference.md
      - Exception: api/exceptions.md
      - Signal: api/signals.md
      - Serializer: api/serializers.md
      - OTP Backend:
          - Base: api/backends/base.md
          - Email: api/backends/email.md
          - Twilio SMS: api/backends/twilio.md
          - Authenticator App: api/backends/authenticator.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: google

theme:
  name: readthedocs
  highlightjs: true

markdown_extensions:
  smarty: {}
  toc:
    permalink: true
  sane_lists: {}
